spring:
  data:
    mongodb:
      host: 172.31.249.11:9042
      port: 27017
      database: dilemma
  rabbitmq:
    host: 172.31.249.11
    username: rabbitmq
    password: rabbitmq
    virtual-host: rabbitmq
    port: 5672
messaging:
  rabbitmq:
    messaging-queue: messaging-queue
server:
  port: 8080
management:
  info:
    build:
      enabled: true
    git:
      enabled: true